exports.FILE_MIMES = {

    'all' : [
        'application/octet-stream',
        //applications
        'application/postscript',
        'application/pdf',
        'application/x-shockwave-flash',
        'application/xhtml+xml',
        'application/xml',
        'application/rtf',
        'application/vnd.oasis.opendocument.text',
        'application/x-cocoa',
        'application/x-java-archive-diff',
        'application/x-java-jnlp-file',
        'application/x-makeself',
        'application/x-perl',
        'application/x-pilot',
        'application/x-redhat-package-manager',
        'application/x-sea',
        'application/x-stuffit',
        'application/x-tcl',
        'application/x-x509-ca-cert',
        'application/x-xpinstall',
        'application/vnd.wap.wmlc',
        'application/vnd.google-earth.kml+xml',
        'application/vnd.google-earth.kmz',
        'application/java-archive',
        'application/mac-binhex40',
        'application/x-javascript',
        'application/atom+xml',
        'application/rss+xml',
        //documents
        'application/msword',
        'application/vnd.ms-word',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
        'application/vnd.ms-excel',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
        'application/vnd.ms-powerpoint',
        'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'application/vnd.openxmlformats-officedocument.presentationml.template',
        'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
        'application/kswps',
        // archives
        'application/x-gzip',
        'application/x-bzip2',
        'application/zip',
        'application/x-rar',
        'application/x-tar',
        'application/x-7z-compressed',
        'application/x-rar-compressed',
        // texts
        'text/plain',
        'text/x-php',
        'text/html',
        'text/xml',
        'text/javascript',
        'text/css',
        'text/rtf',
        'text/rtfd',
        'text/x-python',
        'text/x-java-source',
        'text/x-ruby',
        'text/x-shellscript',
        'text/x-perl',
        'text/x-sql',
        'text/x-component',
        'text/vnd.wap.wml',
        'text/vnd.sun.j2me.app-descriptor',
        'text/mathml',
        // images
        'image/x-ms-bmp',
        'image/jpeg',
        'image/gif',
        'image/png',
        'image/tiff',
        'image/x-targa',
        'image/vnd.adobe.photoshop',
        'image/vnd.wap.wbmp',
        'image/x-icon',
        'image/x-jng',
        'image/svg+xml',
        'image/webp',
        //audio
        'audio/mpeg',
        'audio/midi',
        'audio/ogg',
        'audio/mp4',
        'audio/wav',
        'audio/x-ms-wma',
        'audio/x-m4a',
        'audio/x-realaudio',
        // video
        'video/3gpp',
        'video/mp4',
        'video/mpeg',
        'video/quicktime',
        'video/webm',
        'video/x-flv',
        'video/x-m4v',
        'video/x-mng',
        'video/x-dv',
        'video/x-ms-asf',
        'video/x-ms-wmv',
        'video/x-msvideo',
        'video/x-matroska'
    ],

    'image' : [
        'image/x-ms-bmp',
        'image/jpeg',
        'image/gif',
        'image/png',
        'image/tiff',
        'image/x-targa',
        'image/vnd.adobe.photoshop',
        'image/vnd.wap.wbmp',
        'image/x-icon',
        'image/x-jng',
        'image/svg+xml',
        'image/webp'
    ],

    'document' : [
        'application/msword',
        'application/vnd.ms-word',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
        'application/vnd.ms-excel',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
        'application/vnd.ms-powerpoint',
        'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'application/vnd.openxmlformats-officedocument.presentationml.template',
        'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
        'application/kswps'
    ],

    'pdf' : [
        'application/pdf'
    ],

    'audio' : [
        'audio/mpeg',
        'audio/midi',
        'audio/ogg',
        'audio/mp4',
        'audio/wav',
        'audio/x-ms-wma',
        'audio/x-m4a',
        'audio/x-realaudio'
    ],

    'video' : [
        'video/3gpp',
        'video/mp4',
        'video/mpeg',
        'video/quicktime',
        'video/webm',
        'video/x-flv',
        'video/x-m4v',
        'video/x-mng',
        'video/x-dv',
        'video/x-ms-asf',
        'video/x-ms-wmv',
        'video/x-msvideo',
        'video/x-matroska'
    ],

    'application' : [
        'application/postscript',
        'application/pdf',
        'application/x-shockwave-flash',
        'application/xhtml+xml',
        'application/xml',
        'application/rtf',
        'application/vnd.oasis.opendocument.text',
        'application/x-cocoa',
        'application/x-java-archive-diff',
        'application/x-java-jnlp-file',
        'application/x-makeself',
        'application/x-perl',
        'application/x-pilot',
        'application/x-redhat-package-manager',
        'application/x-sea',
        'application/x-stuffit',
        'application/x-tcl',
        'application/x-x509-ca-cert',
        'application/x-xpinstall',
        'application/vnd.wap.wmlc',
        'application/vnd.google-earth.kml+xml',
        'application/vnd.google-earth.kmz',
        'application/java-archive',
        'application/mac-binhex40',
        'application/x-javascript',
        'application/atom+xml',
        'application/rss+xml'
    ],

    'archive' : [
        'application/x-gzip',
        'application/x-bzip2',
        'application/zip',
        'application/x-rar',
        'application/x-tar',
        'application/x-7z-compressed',
        'application/x-rar-compressed'
    ]
};
exports.FILE_SUFFIX = {
    // 后缀 类型
    'all' : [
        //applications
        'ai',
        'eps',
        'exe',
        'xml',
        'odt',
        'swf',
        //documents
        'doc',
        'dot',
        'docx',
        'dotx',
        'xls',
        'xlsx',
        'ppt',
        'pps',
        'pptx',
        'ppsx',
        'et',
        'wps',
        'wpp',
        'dps',
        //pdf
        'pdf',
        // archi
        'gz',
        'tgz',
        'bz',
        'bz2',
        'tbz',
        'zip',
        'rar',
        'tar',
        '7z',
        // texts
        'txt',
        'php',
        'html',
        'htm',
        'js',
        'css',
        'rtf',
        'rtfd',
        'py',
        'java',
        'rb',
        'sh',
        'pl',
        'sql',
        // image
        'bmp',
        'jpg',
        'jpeg',
        'gif',
        'png',
        'tif',
        'tiff',
        'tga',
        'psd',
        'wbmp',
        'ico',
        'svg',
        'svgz',
        'webp',
        //audio
        'mp3',
        'mid',
        'midi',
        'kar',
        'ogg',
        'mp4a',
        'wav',
        'wma',
        'm4a',
        'ra',
        // video
        'avi',
        'dv',
        'mp4',
        'mpeg',
        'mpg',
        'mov',
        'wm',
        'flv',
        'mkv',
        '3gpp',
        '3gp',
        'webm',
        'm4v',
        'mng',
        'asx',
        'asf',
        'wmv'
    ],

    'image' : [
        'bmp',
        'jpg',
        'jpeg',
        'gif',
        'png',
        'tif',
        'tiff',
        'tga',
        'psd',
        'wbmp',
        'ico',
        'svg',
        'svgz',
        'webp'
    ],

    'document' : [
        'doc',
        'dot',
        'docx',
        'dotx',
        'xls',
        'xlsx',
        'ppt',
        'pps',
        'pptx',
        'ppsx',
        'et',
        'wps',
        'wpp',
        'dps'
    ],

    'pdf' : [
        'pdf'
    ],

    'audio' : [
        'mp3',
        'mid',
        'midi',
        'kar',
        'ogg',
        'mp4a',
        'wav',
        'wma',
        'm4a',
        'ra'
    ],

    'video' : [
        'avi',
        'dv',
        'mp4',
        'mpeg',
        'mpg',
        'mov',
        'wm',
        'flv',
        'mkv',
        '3gpp',
        '3gp',
        'webm',
        'm4v',
        'mng',
        'asx',
        'asf',
        'wmv'
    ],

    'application' : [
        'ai',
        'eps',
        'exe',
        'xml',
        'odt',
        'swf'
    ],

    'archive' : [
        'ai',
        'eps',
        'exe',
        'xml',
        'odt',
        'swf'
    ]
}